\  LIKE WORDS EXCEPT IT PRINT WORD COUNT 
: LIST CR 0 0 >R LAST @ BEGIN
DUP COUNT $1F AND DUP R> + >R TYPE SPACE
R@ 70 > IF CR R> DROP 0 >R THEN
SWAP 1+ SWAP CELL- @ ?DUP WHILE
REPEAT R> DROP CR . ;


